.TH pt 1

.SH NAME
.B pt
- presentating text in terminal.

.SH SYNOPSIS
pt
[\fIOPTIONS\fR] \fIfilepath\fR

.SH OPTIONS

.TP
.B -c number
setting up the begging of terminal's columns for all text

.TP
.B -r number
setting up the begging of terminal's rows for all text

.TP
.B -cen, --center
setting text alignment in the center

.SH AUTHOR
Ilya Grigoriev

.SH COPYRIGHT
See the LICENSE file for the terms of redistribution.

